version: "3"
services:
  api:
    build:
      context: ./api
      args:
        - COMMON_FRONTEND_URL=${COMMON_FRONTEND_URL}
        - COMMON_BACKEND_URL=${COMMON_BACKEND_URL}
        - COMMON_STRIPE_YEARLY_PLAN_ID=${COMMON_STRIPE_YEARLY_PLAN_ID}
        - COMMON_STRIPE_MONTHLY_PLAN_ID=${COMMON_STRIPE_MONTHLY_PLAN_ID}
        - PRISMA_ENDPOINT=${PRISMA_ENDPOINT}
        - PRISMA_SECRET=${PRISMA_SECRET}
        - PRISMA_MANAGEMENT_API_SECRET=${PRISMA_MANAGEMENT_API_SECRET}
        - API_AWS_ACCESS_KEY_ID=${API_AWS_ACCESS_KEY_ID}
        - API_AWS_ACCESS_KEY=${API_AWS_ACCESS_KEY}
        - API_AWS_BUCKET_NAME=${API_AWS_BUCKET_NAME}
        - API_COOKIE_DOMAIN=${API_COOKIE_DOMAIN}
        - API_GOOGLE_CLIENT_ID=${API_GOOGLE_CLIENT_ID}
        - API_GOOGLE_CLIENT_SECRET=${API_GOOGLE_CLIENT_SECRET}
        - API_APP_SECRET=${API_APP_SECRET}
        - API_PORT=${API_PORT}
        - API_STRIPE_API_KEY=${API_STRIPE_API_KEY}
        - API_STRIPE_WEBHOOK_SECRET=${API_STRIPE_WEBHOOK_SECRET}
        - API_CLOUDFRONT_DOMAIN=${API_CLOUDFRONT_DOMAIN}
        - API_AMPLITUDE_API_KEY=${API_AMPLITUDE_API_KEY}
    image: tech-job-hunt/api
    container_name: tech-job-hunt-api
    ports:
      - "4000:4000"
    volumes:
      - ./api/src/:/usr/src/app/src/
  prisma:
    depends_on:
      - db
      - s3
    build:
      context: ./prisma
      args:
        PRISMA_CONFIG: |
          managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
          port: 4466
          databases:
            default:
              connector: mysql
              migrations: true
              host: ${PRISMA_DB_HOST}
              port: 3306
              user: root
              password: ${PRISMA_DB_PASSWORD}
    image: tech-job-hunt/prisma
    ports:
      - "4466:4466"
    restart: always
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PRISMA_DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
  s3:
    image: localstack/localstack:latest
    container_name: tech-job-hunt-s3
    ports:
      - "4572:4572"
      - "8000:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - "./.s3:/tmp/localstack"
  web-app:
    build:
      context: ./web-app
      args:
        - COMMON_BACKEND_URL=${COMMON_BACKEND_URL}
        - COMMON_FRONTEND_URL=${COMMON_FRONTEND_URL}
        - COMMON_STRIPE_YEARLY_PLAN_ID=${COMMON_STRIPE_YEARLY_PLAN_ID}
        - COMMON_STRIPE_MONTHLY_PLAN_ID=${COMMON_STRIPE_MONTHLY_PLAN_ID}
        - WEB_APP_STRIPE_PUBLISHABLE_KEY=${WEB_APP_STRIPE_PUBLISHABLE_KEY}
        - WEB_APP_GOOGLE_API_KEY=${WEB_APP_GOOGLE_API_KEY}
        - WEB_APP_MARKETING_SITE=${WEB_APP_MARKETING_SITE}
        - WEB_APP_SENTRY_DSN=${WEB_APP_SENTRY_DSN}
    image: tech-job-hunt/web-app
    container_name: techjobhunt-web-app
    ports:
      - "3000:3000"
volumes:
  mysql:
