version: '3'
services:
  api:
    build:
      context: ./api
      args:
        - COMMON_FRONTEND_URL=${COMMON_FRONTEND_URL}
        - COMMON_BACKEND_URL=${COMMON_BACKEND_URL}
        - COMMON_STRIPE_YEARLY_PLAN_ID=${COMMON_STRIPE_YEARLY_PLAN_ID}
        - COMMON_STRIPE_MONTHLY_PLAN_ID=${COMMON_STRIPE_MONTHLY_PLAN_ID}
        - API_AWS_ACCESS_KEY_ID=${API_AWS_ACCESS_KEY_ID}
        - API_AWS_ACCESS_KEY=${API_AWS_ACCESS_KEY}
        - API_AWS_BUCKET_NAME=${API_AWS_BUCKET_NAME}
        - API_COOKIE_DOMAIN=${API_COOKIE_DOMAIN}
        - API_GOOGLE_CLIENT_ID=${API_GOOGLE_CLIENT_ID}
        - API_GOOGLE_CLIENT_SECRET=${API_GOOGLE_CLIENT_SECRET}
        - API_APP_SECRET=${API_APP_SECRET}
        - API_PORT=${API_PORT}
        - API_STRIPE_API_KEY=${API_STRIPE_API_KEY}
        - API_STRIPE_WEBHOOK_SECRET=${API_STRIPE_WEBHOOK_SECRET}
        - API_CLOUDFRONT_DOMAIN=${API_CLOUDFRONT_DOMAIN}
        - API_AMPLITUDE_API_KEY=${API_AMPLITUDE_API_KEY}
        - API_DATABASE_URL=${API_DATABASE_URL}
    image: tech-job-hunt/api
    container_name: tech-job-hunt-api
    ports:
      - '4000:4000'
    volumes:
      - ./api/src/:/usr/src/app/src/
